/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.model;

import backend.model.SolicitudTarjeta;

/**
 *
 * @author Carlos Cotom
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        itmenuSolicitudTarjeta = new javax.swing.JMenuItem();
        itmenuMovimientoTarjeta = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        itmenuConsultarTarjeta = new javax.swing.JMenuItem();
        itmenuEstadoCuenta = new javax.swing.JMenuItem();
        itmenuListadoTarjetas = new javax.swing.JMenuItem();
        itmenuListadoSolicitudes = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        itmenuAutorizarTarjeta = new javax.swing.JMenuItem();
        itmenuCancelarTarjeta = new javax.swing.JMenuItem();
        itmenuImportarDatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bancario");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        menuRegistrar.setText("Registrar");

        itmenuSolicitudTarjeta.setText("Solicitud de Tarjeta");
        itmenuSolicitudTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuSolicitudTarjetaActionPerformed(evt);
            }
        });
        menuRegistrar.add(itmenuSolicitudTarjeta);

        itmenuMovimientoTarjeta.setText("Movimiento de Tarjeta");
        itmenuMovimientoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuMovimientoTarjetaActionPerformed(evt);
            }
        });
        menuRegistrar.add(itmenuMovimientoTarjeta);

        jMenuBar1.add(menuRegistrar);

        menuConsultas.setText("Consultar");

        itmenuConsultarTarjeta.setText("Tarjeta");
        itmenuConsultarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuConsultarTarjetaActionPerformed(evt);
            }
        });
        menuConsultas.add(itmenuConsultarTarjeta);

        itmenuEstadoCuenta.setText("Estado de Cuenta");
        itmenuEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuEstadoCuentaActionPerformed(evt);
            }
        });
        menuConsultas.add(itmenuEstadoCuenta);

        itmenuListadoTarjetas.setText("Listado de Tarjetas");
        itmenuListadoTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuListadoTarjetasActionPerformed(evt);
            }
        });
        menuConsultas.add(itmenuListadoTarjetas);

        itmenuListadoSolicitudes.setText("Listado de Solicitudes");
        itmenuListadoSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuListadoSolicitudesActionPerformed(evt);
            }
        });
        menuConsultas.add(itmenuListadoSolicitudes);

        jMenuBar1.add(menuConsultas);

        menuOtros.setText("Otros");

        itmenuAutorizarTarjeta.setText("Autorizar Tarjeta");
        itmenuAutorizarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuAutorizarTarjetaActionPerformed(evt);
            }
        });
        menuOtros.add(itmenuAutorizarTarjeta);

        itmenuCancelarTarjeta.setText("Cancelar Tarjeta");
        itmenuCancelarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuCancelarTarjetaActionPerformed(evt);
            }
        });
        menuOtros.add(itmenuCancelarTarjeta);

        itmenuImportarDatos.setText("Importar Datos");
        itmenuImportarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuImportarDatosActionPerformed(evt);
            }
        });
        menuOtros.add(itmenuImportarDatos);

        jMenuBar1.add(menuOtros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmenuAutorizarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuAutorizarTarjetaActionPerformed
        JIFAutorizacionTarjeta autorizacionTarjeta = new JIFAutorizacionTarjeta();
        this.jDesktopPane1.add(autorizacionTarjeta);
        autorizacionTarjeta.setVisible(true);
    }//GEN-LAST:event_itmenuAutorizarTarjetaActionPerformed

    private void itmenuImportarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuImportarDatosActionPerformed
        JIFIngresoArchivo ingresoArchivo = new JIFIngresoArchivo();
        this.jDesktopPane1.add(ingresoArchivo);
        ingresoArchivo.setVisible(true);
    }//GEN-LAST:event_itmenuImportarDatosActionPerformed

    private void itmenuSolicitudTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuSolicitudTarjetaActionPerformed
        JIFSolicitudTarjeta solicitudTarjeta = new JIFSolicitudTarjeta();
        this.jDesktopPane1.add(solicitudTarjeta);
        solicitudTarjeta.setVisible(true);
    }//GEN-LAST:event_itmenuSolicitudTarjetaActionPerformed

    private void itmenuConsultarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuConsultarTarjetaActionPerformed
        JIFConsultaTarjeta consultaTarjeta = new JIFConsultaTarjeta();
        this.jDesktopPane1.add(consultaTarjeta);
        consultaTarjeta.setVisible(true);
    }//GEN-LAST:event_itmenuConsultarTarjetaActionPerformed

    private void itmenuMovimientoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuMovimientoTarjetaActionPerformed
        JIFMovimientoTarjeta movimientoTarjeta = new JIFMovimientoTarjeta();
        this.jDesktopPane1.add(movimientoTarjeta);
        movimientoTarjeta.setVisible(true);
    }//GEN-LAST:event_itmenuMovimientoTarjetaActionPerformed

    private void itmenuCancelarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuCancelarTarjetaActionPerformed
        JIFCancelacionTarjeta cancelacionTarjeta = new JIFCancelacionTarjeta();
        this.jDesktopPane1.add(cancelacionTarjeta);
        cancelacionTarjeta.setVisible(true);
    }//GEN-LAST:event_itmenuCancelarTarjetaActionPerformed

    private void itmenuListadoTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuListadoTarjetasActionPerformed
        JIFListadoTarjetas listadoTarjetas = new JIFListadoTarjetas();
        this.jDesktopPane1.add(listadoTarjetas);
        listadoTarjetas.setVisible(true);
    }//GEN-LAST:event_itmenuListadoTarjetasActionPerformed

    private void itmenuListadoSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuListadoSolicitudesActionPerformed
        JIFListadoSolicitudes listadoSolicitudes = new JIFListadoSolicitudes();
        this.jDesktopPane1.add(listadoSolicitudes);
        listadoSolicitudes.setVisible(true);
    }//GEN-LAST:event_itmenuListadoSolicitudesActionPerformed

    private void itmenuEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuEstadoCuentaActionPerformed
        JIFEstadoCuenta estadosCuenta = new JIFEstadoCuenta();
        this.jDesktopPane1.add(estadosCuenta);
        estadosCuenta.setVisible(true);
    }//GEN-LAST:event_itmenuEstadoCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmenuAutorizarTarjeta;
    private javax.swing.JMenuItem itmenuCancelarTarjeta;
    private javax.swing.JMenuItem itmenuConsultarTarjeta;
    private javax.swing.JMenuItem itmenuEstadoCuenta;
    private javax.swing.JMenuItem itmenuImportarDatos;
    private javax.swing.JMenuItem itmenuListadoSolicitudes;
    private javax.swing.JMenuItem itmenuListadoTarjetas;
    private javax.swing.JMenuItem itmenuMovimientoTarjeta;
    private javax.swing.JMenuItem itmenuSolicitudTarjeta;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenu menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
