/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend.model;

import backend.data.AutorizacionTarjetaDB;
import backend.model.Bancario;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Cotom
 */
public class JIFAutorizacionTarjeta extends javax.swing.JInternalFrame {

    private Bancario bancario;

    /**
     * Creates new form JIFAutorizacionTarjeta
     */
    public JIFAutorizacionTarjeta() {
        initComponents();
        this.bancario = new Bancario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeroSolicitud = new javax.swing.JTextField();
        btnAutorizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Autorizacion de Tarjeta");

        jLabel1.setText("Numero de Solicitud:");

        btnAutorizar.setText("Autorizar");
        btnAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAutorizar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //---------------------------------------- METODOS DE EVENTO ----------------------------------------//
    private void btnAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarActionPerformed
        if (this.isCamposValidos()) {
            if (bancario.verificarAutorizacionLeida(Integer.parseInt(this.txtNumeroSolicitud.getText()))) {
                AutorizacionTarjetaDB data = new AutorizacionTarjetaDB();
                String numeroTarjeta = data.getNumeroTarjeta(Integer.parseInt(this.txtNumeroSolicitud.getText()));
                JOptionPane.showMessageDialog(this, "Se Autorizo la Tarjeta con Numero " + numeroTarjeta + " para la Solicitud " + this.txtNumeroSolicitud.getText());
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo realizar la Autorizacion");
            }
            this.txtNumeroSolicitud.setText("");
        }
    }//GEN-LAST:event_btnAutorizarActionPerformed

    //---------------------------------------- METODOS PROPIOS ----------------------------------------//
    /**
     * Metodo que evalua cada campo del formulario para verificar que esten
     * completos y de ser asi verificar que sean datos correctos
     *
     * @return verdadero si los campos del formulario son validos, de los
     * contrario retorna falso
     */
    private boolean isCamposValidos() {
        if (this.txtNumeroSolicitud.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe Completar el Campos del Formulario", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isInteger(this.txtNumeroSolicitud.getText())) {
            JOptionPane.showMessageDialog(this, "El Numero de Solicitud ingresado NO es Valido", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isNumeroSolicitudRepetida(Integer.parseInt(this.txtNumeroSolicitud.getText()))) {
            JOptionPane.showMessageDialog(this, "El Numero de Solicitud NO esta Registrada en el Sistema", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumeroSolicitud;
    // End of variables declaration//GEN-END:variables
}
