/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend.model;

import backend.data.EstadoCuentaDB;
import backend.model.Bancario;
import backend.model.EstadoCuenta;
import backend.model.FiltroEstadoCuenta;
import backend.model.MovimientoTarjeta;
import backend.enums.TipoTarjetas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Cotom
 */
public class JIFEstadoCuenta extends javax.swing.JInternalFrame {

    private final DefaultTableModel modeloTabla;
    private Bancario bancario;
    private int indiceDatos;
    private ArrayList<EstadoCuenta> datos;
    
    /**
     * Creates new form JIFEstadoCuenta
     */
    public JIFEstadoCuenta() {
        this.modeloTabla = new DefaultTableModel();
        initComponents();
        this.bancario = new Bancario();
        iniciarTablero();
        this.btnSiguiente.setEnabled(false);
        this.btnAnterior.setEnabled(false);
        this.indiceDatos = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTiposTarjeta = new javax.swing.JComboBox<>();
        txtSaldoMinimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreSolicitante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtInteresMinimo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNumeroTarjeta = new javax.swing.JLabel();
        lblTipoTarjeta = new javax.swing.JLabel();
        lblNombreCLiente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoMovimientos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        lblIntereses = new javax.swing.JLabel();
        lblSaldoTotal = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Estado de Cuenta para Tarjetas Activas");
        setPreferredSize(new java.awt.Dimension(750, 585));

        cmbTiposTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NACIONAL", "REGIONAL", "INTERNACIONAL", "" }));

        jLabel7.setText("Interes Minimo de la Tarjeta:");

        jLabel1.setText("Numero de Tarjeta:");

        jLabel2.setText("Saldo Minimo de la Tarjeta:");

        jLabel3.setText("Tipo de Tarjeta:");

        jLabel4.setText("Nombre del Cliente:");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero de Tarjeta:");

        jLabel6.setText("Tipo de Tarjeta:");

        jLabel8.setText("Nombre Cliente:");

        jLabel9.setText("Direccion Cliente:");

        lblNumeroTarjeta.setText(".");

        lblTipoTarjeta.setText(".");

        lblNombreCLiente.setText(".");

        lblDireccionCliente.setText(".");

        tblListadoMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo de Movimiento", "Descripcion", "Establecimiento", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListadoMovimientos);

        jLabel10.setText("Monto Total:");

        jLabel11.setText("Intereses:");

        jLabel12.setText("Saldo Total:");

        lblMontoTotal.setText(".");

        lblIntereses.setText(".");

        lblSaldoTotal.setText(".");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtInteresMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(90, 90, 90)
                                        .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroTarjeta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNombreCLiente)))
                                .addGap(253, 253, 253)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTipoTarjeta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDireccionCliente))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMontoTotal)
                                        .addGap(233, 233, 233)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIntereses))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblSaldoTotal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAnterior)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnSiguiente))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtInteresMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblNumeroTarjeta)
                    .addComponent(lblTipoTarjeta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lblNombreCLiente)
                    .addComponent(lblDireccionCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(lblMontoTotal)
                    .addComponent(lblIntereses))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblSaldoTotal))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSiguiente)
                            .addComponent(btnAnterior))
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        this.indiceDatos++;
        this.mostrarDatos();
        this.btnAnterior.setEnabled(true);
        if (this.datos.size() == (this.indiceDatos + 1)) {
            this.btnSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (camposValidos()) {
            double saldoMinimo;
            double intereseMinimo;
            FiltroEstadoCuenta filtro;
            if (this.bancario.isDouble(this.txtSaldoMinimo.getText())) {
                saldoMinimo = Double.parseDouble(this.txtSaldoMinimo.getText());
            } else {
                saldoMinimo = -1;
            }
            if (this.bancario.isDouble(this.txtInteresMinimo.getText())) {
                intereseMinimo = Double.parseDouble(this.txtInteresMinimo.getText());
            } else {
                intereseMinimo = -1;
            }
            if (this.bancario.isTipoTarjetaValido(this.cmbTiposTarjeta.getItemAt(this.cmbTiposTarjeta.getSelectedIndex()))) {
                filtro = new FiltroEstadoCuenta(this.txtNumeroTarjeta.getText(),
                    TipoTarjetas.valueOf(this.cmbTiposTarjeta.getItemAt(this.cmbTiposTarjeta.getSelectedIndex())), saldoMinimo, intereseMinimo);
            } else {
                filtro = new FiltroEstadoCuenta(this.txtNumeroTarjeta.getText(), saldoMinimo, intereseMinimo);
            }
            if (this.bancario.verificarFiltroEstadoCuenta(filtro)) {
                String restoQuery = filtro.filtrarDatos();
                EstadoCuentaDB listadoSolicitudes = new EstadoCuentaDB();
                ArrayList<EstadoCuenta> datosEstadoCuenta = listadoSolicitudes.getEstadosCuenta(restoQuery);
                filtro.setDatosEstadosCuenta(datosEstadoCuenta);
                filtro.filtrarEstadosCuenta();
                this.datos = filtro.getDatosEstadosCuenta();
                if (this.datos.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No hay Datos por Mostrar");
                    vaciarTabla();
                    vaciarCampos();
                    return;
                }
                habilitarBotones();
                mostrarDatos();  
            } else {
                JOptionPane.showMessageDialog(this, "Consulta para los Estados de Cuenta NO Valido para su Ejecucion. Vuelva a revisar los Campos Rellenados");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        this.indiceDatos--;
        this.mostrarDatos();
        this.btnSiguiente.setEnabled(true);
        if (this.indiceDatos == 0) {
            this.btnAnterior.setEnabled(false);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private boolean camposValidos() {
        if (this.cmbTiposTarjeta.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No se seleccionó un Tipo de Tarjeta valido", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void habilitarBotones() {
        if (this.datos.size() == (this.indiceDatos + 1)) {
            this.btnSiguiente.setEnabled(false);
        } else {
            this.btnSiguiente.setEnabled(true);                            
        }
    }
    
    private void mostrarDatos() {
        this.lblNumeroTarjeta.setText(this.datos.get(this.indiceDatos).getNumeroTarjeta());
        this.lblTipoTarjeta.setText(this.datos.get(this.indiceDatos).getTipoTarjeta().toString());
        this.lblNombreCLiente.setText(this.datos.get(this.indiceDatos).getNombreCliente());
        this.lblDireccionCliente.setText(this.datos.get(this.indiceDatos).getDireccionCliente());
        vaciarTabla();        
        llenarTabla(this.datos.get(this.indiceDatos).getMovimientos());
        this.lblMontoTotal.setText(this.datos.get(this.indiceDatos).getMontoTotalEjecutado() + "");
        this.lblIntereses.setText(this.datos.get(this.indiceDatos).getIntereses()+ "");
        this.lblSaldoTotal.setText(this.datos.get(this.indiceDatos).getSaldoTotal()+ "");
    }
    
    private void llenarTabla(ArrayList<MovimientoTarjeta> datosMovimiento) {                
        Object[] fila;
        for (int i = 0; i < datosMovimiento.size(); i++) {
            fila = new Object[5];
            fila[0] = datosMovimiento.get(i).getFechaOperacion();
            fila[1] = datosMovimiento.get(i).getTipoMovimiento();
            fila[2] = datosMovimiento.get(i).getDescripcion();
            fila[3] = datosMovimiento.get(i).getEstablecimiento();
            fila[4] = datosMovimiento.get(i).getMontoTransferido();
            this.modeloTabla.addRow(fila);
        }
    }
    
    private void vaciarTabla() {
        this.tblListadoMovimientos.removeAll();
        int filasTabla = this.modeloTabla.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {            
                this.modeloTabla.removeRow(0);           
            }            
        }
    }
    
    private void vaciarCampos() {
        this.lblDireccionCliente.setText("");
        this.lblIntereses.setText("");
        this.lblMontoTotal.setText("");
        this.lblNombreCLiente.setText("");
        this.lblNumeroTarjeta.setText("");
        this.lblSaldoTotal.setText("");
        this.lblTipoTarjeta.setText("");
    }
    
    private void iniciarTablero() {
        this.tblListadoMovimientos.setModel(modeloTabla);
        this.modeloTabla.addColumn("Fecha");
        this.modeloTabla.addColumn("Tipo de Movimiento");
        this.modeloTabla.addColumn("Descripcion");
        this.modeloTabla.addColumn("Establecimiento");
        this.modeloTabla.addColumn("Monto");
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbTiposTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblIntereses;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNombreCLiente;
    private javax.swing.JLabel lblNumeroTarjeta;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JLabel lblTipoTarjeta;
    private javax.swing.JTable tblListadoMovimientos;
    private javax.swing.JTextField txtInteresMinimo;
    private javax.swing.JTextField txtNombreSolicitante;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JTextField txtSaldoMinimo;
    // End of variables declaration//GEN-END:variables
}
