/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend.model;

import backend.data.CancelacionTarjetaDB;
import backend.model.LectorArchivo;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Carlos Cotom
 */
public class JIFIngresoArchivo extends javax.swing.JInternalFrame {

    private LectorArchivo lector;
    private int respuestaArchivo;
    private int respuestaCarpeta;
    private String pathCarpeta;

    public String getPathCarpeta() {
        return pathCarpeta;
    }

    public void setPathCarpeta(String pathCarpeta) {
        this.pathCarpeta = pathCarpeta;
    }  

    public JDialog getConfirmacionDialog() {
        return confirmacionDialog;
    }

    public void setConfirmacionDialog(JDialog confirmacionDialog) {
        this.confirmacionDialog = confirmacionDialog;
    }    

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public void setLblDireccion(JLabel lblDireccion) {
        this.lblDireccion = lblDireccion;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblSalario() {
        return lblSalario;
    }

    public void setLblSalario(JLabel lblSalario) {
        this.lblSalario = lblSalario;
    }   

    public JLabel getLblNumeroTarjeta() {
        return lblNumeroTarjeta;
    }

    public void setLblNumeroTarjeta(JLabel lblNumeroTarjeta) {
        this.lblNumeroTarjeta = lblNumeroTarjeta;
    }    
    
    /**
     * Creates new form JIFIngresoArchivo
     */
    public JIFIngresoArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        confirmacionDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumeroTarjeta = new javax.swing.JLabel();
        btnSeleccionarArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSeleccionarRuta = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        lblDescripcionProceso = new javax.swing.JLabel();

        confirmacionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        confirmacionDialog.setTitle("Confirmacion para Cancelar Tarjeta");
        confirmacionDialog.setSize(new java.awt.Dimension(450, 280));

        jLabel4.setText("¿Seguro que quiere Cancelar la Tarjeta del Propietario siguiente?");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre del Propietario:");

        jLabel6.setText("Direccion del Propietario:");

        jLabel7.setText("Salario del Propietario:");

        lblDireccion.setText(".");

        lblNombre.setText(".");

        lblSalario.setText(".");

        jLabel8.setText("Numero Tarjeta:");

        lblNumeroTarjeta.setText(".");

        javax.swing.GroupLayout confirmacionDialogLayout = new javax.swing.GroupLayout(confirmacionDialog.getContentPane());
        confirmacionDialog.getContentPane().setLayout(confirmacionDialogLayout);
        confirmacionDialogLayout.setHorizontalGroup(
            confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmacionDialogLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(54, 54, 54))
            .addGroup(confirmacionDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(confirmacionDialogLayout.createSequentialGroup()
                        .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroTarjeta)
                            .addComponent(lblSalario)
                            .addComponent(lblNombre)
                            .addComponent(lblDireccion))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        confirmacionDialogLayout.setVerticalGroup(
            confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmacionDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNumeroTarjeta))
                .addGap(18, 18, 18)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDireccion))
                .addGap(18, 18, 18)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSalario))
                .addGap(35, 35, 35)
                .addGroup(confirmacionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(43, 43, 43))
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Carga de Archivo");

        btnSeleccionarArchivo.setText("Seleccionar Archivo");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Procesando:");

        lblCarga.setText(".");

        jLabel2.setText("Ingrese la Velocidad en Mili Segundos para Procesar cada Instruccion del Archivo Seleccionado:");

        jLabel3.setText("Seleccione la Ruta donde Quiere Recibir los Posibles Reportes:");

        btnSeleccionarRuta.setText("Seleccionar Ruta");
        btnSeleccionarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarRutaActionPerformed(evt);
            }
        });

        btnProcesar.setText("Procesar Archivo");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        lblDescripcionProceso.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionarRuta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCarga))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblDescripcionProceso))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(btnSeleccionarArchivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(btnProcesar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnSeleccionarArchivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(btnSeleccionarRuta))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblCarga))
                .addGap(18, 18, 18)
                .addComponent(lblDescripcionProceso)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.txt", "txt");
        jFileChooser1.setFileFilter(filtro);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser1.setVisible(true);
        respuestaArchivo = jFileChooser1.showOpenDialog(this);
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnSeleccionarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarRutaActionPerformed
        jFileChooser2.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser2.setVisible(true);
        respuestaCarpeta = jFileChooser2.showOpenDialog(this);
    }//GEN-LAST:event_btnSeleccionarRutaActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if (this.validarCampos()) {
            this.btnProcesar.setEnabled(false);
            this.btnSeleccionarArchivo.setEnabled(false);
            this.btnSeleccionarRuta.setEnabled(false);
            this.lector.start();            
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        CancelacionTarjetaDB cancelacion = new CancelacionTarjetaDB();
        cancelacion.actualizarEstadoTarjeta(this.lblNumeroTarjeta.getText());
        JOptionPane.showMessageDialog(this, "Tarjeta Cancelada Exitosamente");
        this.confirmacionDialog.dispose();
        this.lector.getBarraCarga().reanudar();
        this.lector.reanudar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        JOptionPane.showMessageDialog(this, "Accion Cancelada");
        this.confirmacionDialog.dispose();
        this.lector.getBarraCarga().reanudar();
        this.lector.reanudar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private boolean validarCampos() {                  
        if (respuestaArchivo != jFileChooser1.APPROVE_OPTION || jFileChooser1.getSelectedFile() == null) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar el Archivo a Procesar", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (respuestaCarpeta != jFileChooser2.APPROVE_OPTION || jFileChooser2.getSelectedFile() == null) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar la Carpeta para Guardar los Posibles Reportes", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        this.pathCarpeta = jFileChooser2.getSelectedFile().getAbsolutePath();
        System.out.println(this.pathCarpeta);
        if (this.txtTiempo.getText() == "" || this.txtTiempo.getText() == null || this.txtTiempo.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar el Tiempo de Porcesamiento para el Archivo Seleccionado", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        this.lector = new LectorArchivo(jFileChooser1.getSelectedFile(), this, lblCarga, lblDescripcionProceso, Integer.parseInt(this.txtTiempo.getText()));
        return true;
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnSeleccionarRuta;
    private javax.swing.JDialog confirmacionDialog;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCarga;
    private javax.swing.JLabel lblDescripcionProceso;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroTarjeta;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
