/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend.model;

import backend.data.ListadoTarjetasDB;
import backend.enums.EstadosTarjeta;
import backend.model.Bancario;
import backend.model.ListadoTarjetas;
import backend.enums.TipoTarjetas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Cotom
 */
public class JIFListadoTarjetas extends javax.swing.JInternalFrame {

    private final DefaultTableModel modeloTabla;
    private Bancario bancario;

    /**
     * Creates new form JIFListadoTarjetas
     */
    public JIFListadoTarjetas() {
        this.modeloTabla = new DefaultTableModel();
        initComponents();
        this.bancario = new Bancario();
        iniciarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEstadoTarjeta = new javax.swing.JComboBox<>();
        txtLimiteTarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTiposTarjeta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoTarjetas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listado de Tarjetas dentro del Sistema Bancario");

        cmbEstadoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUTORIZADA", "CANCELADA", "" }));

        jLabel1.setText("Tipo de Tarjeta:");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel2.setText("Limite Minimo de la Tarjeta:");

        jLabel3.setText("Estado de la Tarjeta:");

        jLabel4.setText("Fecha Inicio:");

        jLabel5.setText("Fecha Fin:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Formato fecha: dd/mm/aaaa");

        cmbTiposTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NACIONAL", "REGIONAL", "INTERNACIONAL", "" }));

        tblListadoTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Tarjeta", "Tipo de Tarjeta", "Limite", "Nombre del Cliente", "Direccion del Cliente", "Fecha de Ultimo Estado", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListadoTarjetas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(53, 53, 53)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLimiteTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstadoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnConsultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtLimiteTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbEstadoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //---------------------------------------- METODOS DE EVENTO ----------------------------------------//
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (camposValidos()) {
            double montoLimite;
            ListadoTarjetas filtro;
            if (this.bancario.isDouble(this.txtLimiteTarjeta.getText())) {
                montoLimite = Double.parseDouble(this.txtLimiteTarjeta.getText());
            } else {
                montoLimite = -1;
            }
            filtro = new ListadoTarjetas(montoLimite, this.txtFechaInicio.getText(), this.txtFechaFin.getText());
            if (this.bancario.isTipoTarjetaValido(this.cmbTiposTarjeta.getItemAt(this.cmbTiposTarjeta.getSelectedIndex()))) {
                filtro.setTipoTarjeta(TipoTarjetas.valueOf(this.cmbTiposTarjeta.getItemAt(this.cmbTiposTarjeta.getSelectedIndex())));
                filtro.setHayTipoTarjeta(true);
            } else {
                filtro.setHayTipoTarjeta(false);
            }
            if (this.bancario.isEstadoTarjetaValido(this.cmbEstadoTarjeta.getItemAt(this.cmbEstadoTarjeta.getSelectedIndex()))) {
                filtro.setEstadoTarjeta(EstadosTarjeta.valueOf(this.cmbEstadoTarjeta.getItemAt(this.cmbEstadoTarjeta.getSelectedIndex())));
                filtro.setHayEstadoTarjeta(true);
            } else {
                filtro.setHayEstadoTarjeta(false);
            }
            if (this.bancario.verificarFiltroListadoTarjetas(filtro)) {
                String restoQuery = filtro.filtrarDatos();
                ListadoTarjetasDB listadoTarjetas = new ListadoTarjetasDB();
                ArrayList<ListadoTarjetas> datos = listadoTarjetas.getListadoTarjetas(restoQuery);
                if (datos.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No hay Datos por Mostrar");
                    vaciarTabla();
                    vaciarCampos();
                    return;
                }
                llenarTabla(datos);
                vaciarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Consulta de Listado de Tarjetas NO Valido para su Ejecucion. Vuelva a revisar los Campos Rellenados");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    //---------------------------------------- METODOS PROPIOS ----------------------------------------//
    /**
     * Metodo que evalua cada campo del formulario para verificar que esten
     * completos y de ser asi verificar que sean datos correctos
     *
     * @return verdadero si los campos del formulario son validos, de los
     * contrario retorna falso
     */
    private boolean camposValidos() {
        if (this.cmbEstadoTarjeta.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No se seleccionó un tipode Movimiento valido", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (this.cmbTiposTarjeta.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No se seleccionó un tipode Movimiento valido", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.txtLimiteTarjeta.getText().equals("") && !this.bancario.isDouble(this.txtLimiteTarjeta.getText())) {
            JOptionPane.showMessageDialog(this, "El valor ingresado en el Campo de Limite Minimo no es Valido", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * Metodo que muestra en la Tabla de la interfaz los datos de cada Tarjeta
     * que esta en el Array recibido como parametro
     *
     * @param datos son los datos de cada tarjeta registrarda en sistema
     */
    private void llenarTabla(ArrayList<ListadoTarjetas> datos) {
        vaciarTabla();
        Object[] fila;
        for (int i = 0; i < datos.size(); i++) {
            fila = new Object[7];
            fila[0] = datos.get(i).getNumeroTarjeta();
            fila[1] = datos.get(i).getTipoTarjeta();
            fila[2] = datos.get(i).getLimiteCreditoTarjeta();
            fila[3] = datos.get(i).getNombreCliente();
            fila[4] = datos.get(i).getDireccionCliente();
            fila[5] = datos.get(i).getFechaCambioEstado();
            fila[6] = datos.get(i).getEstadoTarjeta();
            this.modeloTabla.addRow(fila);
        }
        JOptionPane.showMessageDialog(this, "Consulta Exitosa!!!");
    }

    /**
     * Metodo que limpia la Tabla de la Interfaz para no tener problemas de
     * colapsos
     */
    private void vaciarTabla() {
        this.tblListadoTarjetas.removeAll();
        int filasTabla = this.modeloTabla.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modeloTabla.removeRow(0);
            }
        }
    }

    /**
     * Metodo que limpia los campos en donde se ingresaron los datos para la
     * busqueda
     */
    private void vaciarCampos() {
        this.txtFechaFin.setText("");
        this.txtFechaInicio.setText("");
        this.txtLimiteTarjeta.setText("");
    }

    /**
     * Metodo que le da a la Tabla de la interfaz el modelo adecuado para su
     * visualizacion
     */
    private void iniciarTablero() {
        this.tblListadoTarjetas.setModel(modeloTabla);
        this.modeloTabla.addColumn("Numero de Tarjeta");
        this.modeloTabla.addColumn("Tipo Tarjeta");
        this.modeloTabla.addColumn("Limite");
        this.modeloTabla.addColumn("Nombre del Clente");
        this.modeloTabla.addColumn("Direccion del Cliente");
        this.modeloTabla.addColumn("Fecha de Ultimo Estado");
        this.modeloTabla.addColumn("Estado");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbEstadoTarjeta;
    private javax.swing.JComboBox<String> cmbTiposTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblListadoTarjetas;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtLimiteTarjeta;
    // End of variables declaration//GEN-END:variables
}
