/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend.model;

import backend.model.Bancario;
import backend.model.SolicitudTarjeta;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Cotom
 */
public class JIFSolicitudTarjeta extends javax.swing.JInternalFrame {

    private Bancario bancario;
    
    /**
     * Creates new form JIFSolicitudTarjeta
     */
    public JIFSolicitudTarjeta() {
        initComponents();
        this.bancario = new Bancario();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeroSolicitud = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreSolicitante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSalarioSolicitante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionSolicitante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbTiposTarjeta = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Solicitud de Tarjeta");

        jLabel1.setText("Numero de Solicitud: ");

        jLabel2.setText("Fecha de Solicitud: ");

        jLabel3.setText("Tipo de Tarjeta Solicitada:");

        jLabel4.setText("Nombre del Solicitante:");

        jLabel5.setText("Salario del Solicitante:");

        jLabel6.setText("Direccion del Solicitante:");

        cmbTiposTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NACIONAL", "REGIONAL", "INTERNACIONAL" }));

        jLabel7.setText("Formato fecha: dd/mm/aaaa");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(txtSalarioSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionSolicitante)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSalarioSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccionSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (this.camposValidos()) {
            SolicitudTarjeta solicitud = new SolicitudTarjeta(Integer.parseInt(this.txtNumeroSolicitud.getText()), this.txtFecha.getText(),
                    this.cmbTiposTarjeta.getItemAt(this.cmbTiposTarjeta.getSelectedIndex()), this.txtNombreSolicitante.getText(),
                    Double.parseDouble(this.txtSalarioSolicitante.getText()), this.txtDireccionSolicitante.getText());
            if (this.bancario.verificarSolicitudLeida(solicitud)) {
                JOptionPane.showMessageDialog(this, "Solicitud Registrada Exitosamente!!!");
                this.txtNumeroSolicitud.setText("");
                this.txtFecha.setText("");
                this.txtNombreSolicitante.setText("");
                this.txtSalarioSolicitante.setText("");
                this.txtDireccionSolicitante.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "La Solicitud NO se pudo Registrar por favor Vuelva a Revisar los Datos de cada Campo en el Formulario");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private boolean camposValidos() {
        if ("".equals(this.txtNumeroSolicitud.getText()) || "".equals(this.txtFecha.getText())
                || "".equals(this.txtNombreSolicitante.getText()) || "".equals(this.txtSalarioSolicitante.getText())
                || "".equals(this.txtDireccionSolicitante.getText())) {
            JOptionPane.showMessageDialog(this, "Debe Completar TODOS los Campos del Formulario", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isDouble(this.txtSalarioSolicitante.getText())) {
            JOptionPane.showMessageDialog(this, "Debe Colocar un Numero Decimal Positivo en el Campo de Salario del Solicitante", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isInteger(this.txtNumeroSolicitud.getText())) {
            JOptionPane.showMessageDialog(this, "Debe Colocar un Numero Entero Positivo en el Campo de Numero de Solicitud", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (this.bancario.isNumeroSolicitudRepetida(Integer.parseInt(this.txtNumeroSolicitud.getText()))) {
            JOptionPane.showMessageDialog(this, "NO puede Ingresar un Numero de Solicitud Repetida", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isFormatoFechaCorrecto(this.txtFecha.getText())) {
            JOptionPane.showMessageDialog(this, "El Formato de Fecha NO es Correcto", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (this.cmbTiposTarjeta.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No se seleccionó un Tipo de Tarjeta Valida", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isLongitudCadenaValida(this.txtNombreSolicitante.getText(), 100)) {
            JOptionPane.showMessageDialog(this, "El Nombre de Solicitante es MUY Largo", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!this.bancario.isLongitudCadenaValida(this.txtDireccionSolicitante.getText(), 150)) {
            JOptionPane.showMessageDialog(this, "La Direccion del Solicitante es MUY Largo", "Error!!!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTiposTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDireccionSolicitante;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreSolicitante;
    private javax.swing.JTextField txtNumeroSolicitud;
    private javax.swing.JTextField txtSalarioSolicitante;
    // End of variables declaration//GEN-END:variables
}
